sonar.projectKey=svzzin_solarsystem
sonar.organization=trial-sonar
sonar.coverage.exclusions=**/test/**,**/tests/**,**/Test/**,**/Tests/**,**/*Test.java,**/*Tests.java
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=solarsystem
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8